apiVersion: v1
kind: Service
metadata:
  name: k8s-grpc-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: grpc-endpoint
  type: NodePort
  selector:
    app: k8s-grpc
